name: CoopR CI Build

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Checkout Main Branch from GitHub
        uses: actions/checkout@v3

      - name: Step 2 - Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Step 3 - Have GitHub Actions Build Maven Project
        run: |
        cd CoopR-HQ
        mvn clean install
