name: Deploy to Development

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Step 1 - Checkout Main Branch from GitHub
      uses: actions/checkout@v3
    
    - name: Step 2 - Build Testing Release
      run: |
        cd CoopR-Mod
        chmod +x ./build_release.sh
        ./build_release.sh
