name: Deploy to Development

on:
  push:
    branches: 
      - development

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build Testing Release
      run: |
        chmod +x ./build_release.sh
        ./build_release.sh
